// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lldwszqmdspacdphuqeh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxsZHdzenFtZHNwYWNkcGh1cWVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMjYxNTcsImV4cCI6MjA2NjcwMjE1N30.M-j9QZc--VdFzUub3pO3r5oex85vYHUQHAg7swfZKno";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);